// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class CheckStatus {
    private @Nullable String name;
    private @Nullable String output;
    private @Nullable String status;
    private @Nullable String updatedAt;

    private CheckStatus() {}
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Optional<String> output() {
        return Optional.ofNullable(this.output);
    }
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }
    public Optional<String> updatedAt() {
        return Optional.ofNullable(this.updatedAt);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CheckStatus defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String name;
        private @Nullable String output;
        private @Nullable String status;
        private @Nullable String updatedAt;
        public Builder() {}
        public Builder(CheckStatus defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.output = defaults.output;
    	      this.status = defaults.status;
    	      this.updatedAt = defaults.updatedAt;
        }

        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder output(@Nullable String output) {

            this.output = output;
            return this;
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder updatedAt(@Nullable String updatedAt) {

            this.updatedAt = updatedAt;
            return this;
        }
        public CheckStatus build() {
            final var _resultValue = new CheckStatus();
            _resultValue.name = name;
            _resultValue.output = output;
            _resultValue.status = status;
            _resultValue.updatedAt = updatedAt;
            return _resultValue;
        }
    }
}
