// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyFile {
    private @Nullable String guestPath;
    private @Nullable Integer mode;
    private @Nullable String rawValue;
    private @Nullable String secretName;

    private FlyFile() {}
    public Optional<String> guestPath() {
        return Optional.ofNullable(this.guestPath);
    }
    public Optional<Integer> mode() {
        return Optional.ofNullable(this.mode);
    }
    public Optional<String> rawValue() {
        return Optional.ofNullable(this.rawValue);
    }
    public Optional<String> secretName() {
        return Optional.ofNullable(this.secretName);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyFile defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String guestPath;
        private @Nullable Integer mode;
        private @Nullable String rawValue;
        private @Nullable String secretName;
        public Builder() {}
        public Builder(FlyFile defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.guestPath = defaults.guestPath;
    	      this.mode = defaults.mode;
    	      this.rawValue = defaults.rawValue;
    	      this.secretName = defaults.secretName;
        }

        @CustomType.Setter
        public Builder guestPath(@Nullable String guestPath) {

            this.guestPath = guestPath;
            return this;
        }
        @CustomType.Setter
        public Builder mode(@Nullable Integer mode) {

            this.mode = mode;
            return this;
        }
        @CustomType.Setter
        public Builder rawValue(@Nullable String rawValue) {

            this.rawValue = rawValue;
            return this;
        }
        @CustomType.Setter
        public Builder secretName(@Nullable String secretName) {

            this.secretName = secretName;
            return this;
        }
        public FlyFile build() {
            final var _resultValue = new FlyFile();
            _resultValue.guestPath = guestPath;
            _resultValue.mode = mode;
            _resultValue.rawValue = rawValue;
            _resultValue.secretName = secretName;
            return _resultValue;
        }
    }
}
