// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.flyio.flyio.outputs.FlyEnvFrom;
import com.pulumi.flyio.flyio.outputs.FlyMachineSecret;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyMachineProcess {
    private @Nullable List<String> cmd;
    private @Nullable List<String> entrypoint;
    private @Nullable Map<String,String> env;
    private @Nullable List<FlyEnvFrom> envFrom;
    private @Nullable List<String> exec;
    private @Nullable Boolean ignoreAppSecrets;
    private @Nullable List<FlyMachineSecret> secrets;
    private @Nullable String user;

    private FlyMachineProcess() {}
    public List<String> cmd() {
        return this.cmd == null ? List.of() : this.cmd;
    }
    public List<String> entrypoint() {
        return this.entrypoint == null ? List.of() : this.entrypoint;
    }
    public Map<String,String> env() {
        return this.env == null ? Map.of() : this.env;
    }
    public List<FlyEnvFrom> envFrom() {
        return this.envFrom == null ? List.of() : this.envFrom;
    }
    public List<String> exec() {
        return this.exec == null ? List.of() : this.exec;
    }
    public Optional<Boolean> ignoreAppSecrets() {
        return Optional.ofNullable(this.ignoreAppSecrets);
    }
    public List<FlyMachineSecret> secrets() {
        return this.secrets == null ? List.of() : this.secrets;
    }
    public Optional<String> user() {
        return Optional.ofNullable(this.user);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyMachineProcess defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> cmd;
        private @Nullable List<String> entrypoint;
        private @Nullable Map<String,String> env;
        private @Nullable List<FlyEnvFrom> envFrom;
        private @Nullable List<String> exec;
        private @Nullable Boolean ignoreAppSecrets;
        private @Nullable List<FlyMachineSecret> secrets;
        private @Nullable String user;
        public Builder() {}
        public Builder(FlyMachineProcess defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cmd = defaults.cmd;
    	      this.entrypoint = defaults.entrypoint;
    	      this.env = defaults.env;
    	      this.envFrom = defaults.envFrom;
    	      this.exec = defaults.exec;
    	      this.ignoreAppSecrets = defaults.ignoreAppSecrets;
    	      this.secrets = defaults.secrets;
    	      this.user = defaults.user;
        }

        @CustomType.Setter
        public Builder cmd(@Nullable List<String> cmd) {

            this.cmd = cmd;
            return this;
        }
        public Builder cmd(String... cmd) {
            return cmd(List.of(cmd));
        }
        @CustomType.Setter
        public Builder entrypoint(@Nullable List<String> entrypoint) {

            this.entrypoint = entrypoint;
            return this;
        }
        public Builder entrypoint(String... entrypoint) {
            return entrypoint(List.of(entrypoint));
        }
        @CustomType.Setter
        public Builder env(@Nullable Map<String,String> env) {

            this.env = env;
            return this;
        }
        @CustomType.Setter
        public Builder envFrom(@Nullable List<FlyEnvFrom> envFrom) {

            this.envFrom = envFrom;
            return this;
        }
        public Builder envFrom(FlyEnvFrom... envFrom) {
            return envFrom(List.of(envFrom));
        }
        @CustomType.Setter
        public Builder exec(@Nullable List<String> exec) {

            this.exec = exec;
            return this;
        }
        public Builder exec(String... exec) {
            return exec(List.of(exec));
        }
        @CustomType.Setter
        public Builder ignoreAppSecrets(@Nullable Boolean ignoreAppSecrets) {

            this.ignoreAppSecrets = ignoreAppSecrets;
            return this;
        }
        @CustomType.Setter
        public Builder secrets(@Nullable List<FlyMachineSecret> secrets) {

            this.secrets = secrets;
            return this;
        }
        public Builder secrets(FlyMachineSecret... secrets) {
            return secrets(List.of(secrets));
        }
        @CustomType.Setter
        public Builder user(@Nullable String user) {

            this.user = user;
            return this;
        }
        public FlyMachineProcess build() {
            final var _resultValue = new FlyMachineProcess();
            _resultValue.cmd = cmd;
            _resultValue.entrypoint = entrypoint;
            _resultValue.env = env;
            _resultValue.envFrom = envFrom;
            _resultValue.exec = exec;
            _resultValue.ignoreAppSecrets = ignoreAppSecrets;
            _resultValue.secrets = secrets;
            _resultValue.user = user;
            return _resultValue;
        }
    }
}
