// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyMachineRestart {
    private @Nullable Double gpuBidPrice;
    private @Nullable Integer maxRetries;
    private @Nullable String policy;

    private FlyMachineRestart() {}
    public Optional<Double> gpuBidPrice() {
        return Optional.ofNullable(this.gpuBidPrice);
    }
    public Optional<Integer> maxRetries() {
        return Optional.ofNullable(this.maxRetries);
    }
    public Optional<String> policy() {
        return Optional.ofNullable(this.policy);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyMachineRestart defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Double gpuBidPrice;
        private @Nullable Integer maxRetries;
        private @Nullable String policy;
        public Builder() {}
        public Builder(FlyMachineRestart defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.gpuBidPrice = defaults.gpuBidPrice;
    	      this.maxRetries = defaults.maxRetries;
    	      this.policy = defaults.policy;
        }

        @CustomType.Setter
        public Builder gpuBidPrice(@Nullable Double gpuBidPrice) {

            this.gpuBidPrice = gpuBidPrice;
            return this;
        }
        @CustomType.Setter
        public Builder maxRetries(@Nullable Integer maxRetries) {

            this.maxRetries = maxRetries;
            return this;
        }
        @CustomType.Setter
        public Builder policy(@Nullable String policy) {

            this.policy = policy;
            return this;
        }
        public FlyMachineRestart build() {
            final var _resultValue = new FlyMachineRestart();
            _resultValue.gpuBidPrice = gpuBidPrice;
            _resultValue.maxRetries = maxRetries;
            _resultValue.policy = policy;
            return _resultValue;
        }
    }
}
