// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyMachineSecret {
    private @Nullable String envVar;
    private @Nullable String name;

    private FlyMachineSecret() {}
    public Optional<String> envVar() {
        return Optional.ofNullable(this.envVar);
    }
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyMachineSecret defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String envVar;
        private @Nullable String name;
        public Builder() {}
        public Builder(FlyMachineSecret defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.envVar = defaults.envVar;
    	      this.name = defaults.name;
        }

        @CustomType.Setter
        public Builder envVar(@Nullable String envVar) {

            this.envVar = envVar;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        public FlyMachineSecret build() {
            final var _resultValue = new FlyMachineSecret();
            _resultValue.envVar = envVar;
            _resultValue.name = name;
            return _resultValue;
        }
    }
}
