// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.flyio.flyio.outputs.FlyMachineHTTPHeader;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyMachineCheck {
    private @Nullable String gracePeriod;
    private @Nullable List<FlyMachineHTTPHeader> headers;
    private @Nullable String interval;
    private @Nullable String kind;
    private @Nullable String method;
    private @Nullable String path;
    private @Nullable Integer port;
    private @Nullable String protocol;
    private @Nullable String timeout;
    private @Nullable String tlsServerName;
    private @Nullable Boolean tlsSkipVerify;
    private @Nullable String type;

    private FlyMachineCheck() {}
    public Optional<String> gracePeriod() {
        return Optional.ofNullable(this.gracePeriod);
    }
    public List<FlyMachineHTTPHeader> headers() {
        return this.headers == null ? List.of() : this.headers;
    }
    public Optional<String> interval() {
        return Optional.ofNullable(this.interval);
    }
    public Optional<String> kind() {
        return Optional.ofNullable(this.kind);
    }
    public Optional<String> method() {
        return Optional.ofNullable(this.method);
    }
    public Optional<String> path() {
        return Optional.ofNullable(this.path);
    }
    public Optional<Integer> port() {
        return Optional.ofNullable(this.port);
    }
    public Optional<String> protocol() {
        return Optional.ofNullable(this.protocol);
    }
    public Optional<String> timeout() {
        return Optional.ofNullable(this.timeout);
    }
    public Optional<String> tlsServerName() {
        return Optional.ofNullable(this.tlsServerName);
    }
    public Optional<Boolean> tlsSkipVerify() {
        return Optional.ofNullable(this.tlsSkipVerify);
    }
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyMachineCheck defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String gracePeriod;
        private @Nullable List<FlyMachineHTTPHeader> headers;
        private @Nullable String interval;
        private @Nullable String kind;
        private @Nullable String method;
        private @Nullable String path;
        private @Nullable Integer port;
        private @Nullable String protocol;
        private @Nullable String timeout;
        private @Nullable String tlsServerName;
        private @Nullable Boolean tlsSkipVerify;
        private @Nullable String type;
        public Builder() {}
        public Builder(FlyMachineCheck defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.gracePeriod = defaults.gracePeriod;
    	      this.headers = defaults.headers;
    	      this.interval = defaults.interval;
    	      this.kind = defaults.kind;
    	      this.method = defaults.method;
    	      this.path = defaults.path;
    	      this.port = defaults.port;
    	      this.protocol = defaults.protocol;
    	      this.timeout = defaults.timeout;
    	      this.tlsServerName = defaults.tlsServerName;
    	      this.tlsSkipVerify = defaults.tlsSkipVerify;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder gracePeriod(@Nullable String gracePeriod) {

            this.gracePeriod = gracePeriod;
            return this;
        }
        @CustomType.Setter
        public Builder headers(@Nullable List<FlyMachineHTTPHeader> headers) {

            this.headers = headers;
            return this;
        }
        public Builder headers(FlyMachineHTTPHeader... headers) {
            return headers(List.of(headers));
        }
        @CustomType.Setter
        public Builder interval(@Nullable String interval) {

            this.interval = interval;
            return this;
        }
        @CustomType.Setter
        public Builder kind(@Nullable String kind) {

            this.kind = kind;
            return this;
        }
        @CustomType.Setter
        public Builder method(@Nullable String method) {

            this.method = method;
            return this;
        }
        @CustomType.Setter
        public Builder path(@Nullable String path) {

            this.path = path;
            return this;
        }
        @CustomType.Setter
        public Builder port(@Nullable Integer port) {

            this.port = port;
            return this;
        }
        @CustomType.Setter
        public Builder protocol(@Nullable String protocol) {

            this.protocol = protocol;
            return this;
        }
        @CustomType.Setter
        public Builder timeout(@Nullable String timeout) {

            this.timeout = timeout;
            return this;
        }
        @CustomType.Setter
        public Builder tlsServerName(@Nullable String tlsServerName) {

            this.tlsServerName = tlsServerName;
            return this;
        }
        @CustomType.Setter
        public Builder tlsSkipVerify(@Nullable Boolean tlsSkipVerify) {

            this.tlsSkipVerify = tlsSkipVerify;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        public FlyMachineCheck build() {
            final var _resultValue = new FlyMachineCheck();
            _resultValue.gracePeriod = gracePeriod;
            _resultValue.headers = headers;
            _resultValue.interval = interval;
            _resultValue.kind = kind;
            _resultValue.method = method;
            _resultValue.path = path;
            _resultValue.port = port;
            _resultValue.protocol = protocol;
            _resultValue.timeout = timeout;
            _resultValue.tlsServerName = tlsServerName;
            _resultValue.tlsSkipVerify = tlsSkipVerify;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
