// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyMachineGuest {
    private String cpuKind;
    private Integer cpus;
    private @Nullable String gpuKind;
    private @Nullable Integer gpus;
    private @Nullable String hostDedicationId;
    private @Nullable List<String> kernelArgs;
    private Integer memoryMb;

    private FlyMachineGuest() {}
    public String cpuKind() {
        return this.cpuKind;
    }
    public Integer cpus() {
        return this.cpus;
    }
    public Optional<String> gpuKind() {
        return Optional.ofNullable(this.gpuKind);
    }
    public Optional<Integer> gpus() {
        return Optional.ofNullable(this.gpus);
    }
    public Optional<String> hostDedicationId() {
        return Optional.ofNullable(this.hostDedicationId);
    }
    public List<String> kernelArgs() {
        return this.kernelArgs == null ? List.of() : this.kernelArgs;
    }
    public Integer memoryMb() {
        return this.memoryMb;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyMachineGuest defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String cpuKind;
        private Integer cpus;
        private @Nullable String gpuKind;
        private @Nullable Integer gpus;
        private @Nullable String hostDedicationId;
        private @Nullable List<String> kernelArgs;
        private Integer memoryMb;
        public Builder() {}
        public Builder(FlyMachineGuest defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cpuKind = defaults.cpuKind;
    	      this.cpus = defaults.cpus;
    	      this.gpuKind = defaults.gpuKind;
    	      this.gpus = defaults.gpus;
    	      this.hostDedicationId = defaults.hostDedicationId;
    	      this.kernelArgs = defaults.kernelArgs;
    	      this.memoryMb = defaults.memoryMb;
        }

        @CustomType.Setter
        public Builder cpuKind(String cpuKind) {
            if (cpuKind == null) {
              throw new MissingRequiredPropertyException("FlyMachineGuest", "cpuKind");
            }
            this.cpuKind = cpuKind;
            return this;
        }
        @CustomType.Setter
        public Builder cpus(Integer cpus) {
            if (cpus == null) {
              throw new MissingRequiredPropertyException("FlyMachineGuest", "cpus");
            }
            this.cpus = cpus;
            return this;
        }
        @CustomType.Setter
        public Builder gpuKind(@Nullable String gpuKind) {

            this.gpuKind = gpuKind;
            return this;
        }
        @CustomType.Setter
        public Builder gpus(@Nullable Integer gpus) {

            this.gpus = gpus;
            return this;
        }
        @CustomType.Setter
        public Builder hostDedicationId(@Nullable String hostDedicationId) {

            this.hostDedicationId = hostDedicationId;
            return this;
        }
        @CustomType.Setter
        public Builder kernelArgs(@Nullable List<String> kernelArgs) {

            this.kernelArgs = kernelArgs;
            return this;
        }
        public Builder kernelArgs(String... kernelArgs) {
            return kernelArgs(List.of(kernelArgs));
        }
        @CustomType.Setter
        public Builder memoryMb(Integer memoryMb) {
            if (memoryMb == null) {
              throw new MissingRequiredPropertyException("FlyMachineGuest", "memoryMb");
            }
            this.memoryMb = memoryMb;
            return this;
        }
        public FlyMachineGuest build() {
            final var _resultValue = new FlyMachineGuest();
            _resultValue.cpuKind = cpuKind;
            _resultValue.cpus = cpus;
            _resultValue.gpuKind = gpuKind;
            _resultValue.gpus = gpus;
            _resultValue.hostDedicationId = hostDedicationId;
            _resultValue.kernelArgs = kernelArgs;
            _resultValue.memoryMb = memoryMb;
            return _resultValue;
        }
    }
}
