// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyMachineInit {
    private @Nullable List<String> cmd;
    private @Nullable List<String> entrypoint;
    private @Nullable List<String> exec;
    private @Nullable List<String> kernelArgs;
    private @Nullable Integer swapSizeMb;
    private @Nullable Boolean tty;

    private FlyMachineInit() {}
    public List<String> cmd() {
        return this.cmd == null ? List.of() : this.cmd;
    }
    public List<String> entrypoint() {
        return this.entrypoint == null ? List.of() : this.entrypoint;
    }
    public List<String> exec() {
        return this.exec == null ? List.of() : this.exec;
    }
    public List<String> kernelArgs() {
        return this.kernelArgs == null ? List.of() : this.kernelArgs;
    }
    public Optional<Integer> swapSizeMb() {
        return Optional.ofNullable(this.swapSizeMb);
    }
    public Optional<Boolean> tty() {
        return Optional.ofNullable(this.tty);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyMachineInit defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> cmd;
        private @Nullable List<String> entrypoint;
        private @Nullable List<String> exec;
        private @Nullable List<String> kernelArgs;
        private @Nullable Integer swapSizeMb;
        private @Nullable Boolean tty;
        public Builder() {}
        public Builder(FlyMachineInit defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.cmd = defaults.cmd;
    	      this.entrypoint = defaults.entrypoint;
    	      this.exec = defaults.exec;
    	      this.kernelArgs = defaults.kernelArgs;
    	      this.swapSizeMb = defaults.swapSizeMb;
    	      this.tty = defaults.tty;
        }

        @CustomType.Setter
        public Builder cmd(@Nullable List<String> cmd) {

            this.cmd = cmd;
            return this;
        }
        public Builder cmd(String... cmd) {
            return cmd(List.of(cmd));
        }
        @CustomType.Setter
        public Builder entrypoint(@Nullable List<String> entrypoint) {

            this.entrypoint = entrypoint;
            return this;
        }
        public Builder entrypoint(String... entrypoint) {
            return entrypoint(List.of(entrypoint));
        }
        @CustomType.Setter
        public Builder exec(@Nullable List<String> exec) {

            this.exec = exec;
            return this;
        }
        public Builder exec(String... exec) {
            return exec(List.of(exec));
        }
        @CustomType.Setter
        public Builder kernelArgs(@Nullable List<String> kernelArgs) {

            this.kernelArgs = kernelArgs;
            return this;
        }
        public Builder kernelArgs(String... kernelArgs) {
            return kernelArgs(List.of(kernelArgs));
        }
        @CustomType.Setter
        public Builder swapSizeMb(@Nullable Integer swapSizeMb) {

            this.swapSizeMb = swapSizeMb;
            return this;
        }
        @CustomType.Setter
        public Builder tty(@Nullable Boolean tty) {

            this.tty = tty;
            return this;
        }
        public FlyMachineInit build() {
            final var _resultValue = new FlyMachineInit();
            _resultValue.cmd = cmd;
            _resultValue.entrypoint = entrypoint;
            _resultValue.exec = exec;
            _resultValue.kernelArgs = kernelArgs;
            _resultValue.swapSizeMb = swapSizeMb;
            _resultValue.tty = tty;
            return _resultValue;
        }
    }
}
