// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyMachineHTTPHeader {
    private @Nullable String name;
    private @Nullable List<String> values;

    private FlyMachineHTTPHeader() {}
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public List<String> values() {
        return this.values == null ? List.of() : this.values;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyMachineHTTPHeader defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String name;
        private @Nullable List<String> values;
        public Builder() {}
        public Builder(FlyMachineHTTPHeader defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.values = defaults.values;
        }

        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder values(@Nullable List<String> values) {

            this.values = values;
            return this;
        }
        public Builder values(String... values) {
            return values(List.of(values));
        }
        public FlyMachineHTTPHeader build() {
            final var _resultValue = new FlyMachineHTTPHeader();
            _resultValue.name = name;
            _resultValue.values = values;
            return _resultValue;
        }
    }
}
