// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyStopConfig {
    private @Nullable String signal;
    private @Nullable String timeout;

    private FlyStopConfig() {}
    public Optional<String> signal() {
        return Optional.ofNullable(this.signal);
    }
    public Optional<String> timeout() {
        return Optional.ofNullable(this.timeout);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyStopConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String signal;
        private @Nullable String timeout;
        public Builder() {}
        public Builder(FlyStopConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.signal = defaults.signal;
    	      this.timeout = defaults.timeout;
        }

        @CustomType.Setter
        public Builder signal(@Nullable String signal) {

            this.signal = signal;
            return this;
        }
        @CustomType.Setter
        public Builder timeout(@Nullable String timeout) {

            this.timeout = timeout;
            return this;
        }
        public FlyStopConfig build() {
            final var _resultValue = new FlyStopConfig();
            _resultValue.signal = signal;
            _resultValue.timeout = timeout;
            return _resultValue;
        }
    }
}
