// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyTLSOptions {
    private @Nullable List<String> alpn;
    private @Nullable Boolean defaultSelfSigned;
    private @Nullable List<String> versions;

    private FlyTLSOptions() {}
    public List<String> alpn() {
        return this.alpn == null ? List.of() : this.alpn;
    }
    public Optional<Boolean> defaultSelfSigned() {
        return Optional.ofNullable(this.defaultSelfSigned);
    }
    public List<String> versions() {
        return this.versions == null ? List.of() : this.versions;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyTLSOptions defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<String> alpn;
        private @Nullable Boolean defaultSelfSigned;
        private @Nullable List<String> versions;
        public Builder() {}
        public Builder(FlyTLSOptions defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.alpn = defaults.alpn;
    	      this.defaultSelfSigned = defaults.defaultSelfSigned;
    	      this.versions = defaults.versions;
        }

        @CustomType.Setter
        public Builder alpn(@Nullable List<String> alpn) {

            this.alpn = alpn;
            return this;
        }
        public Builder alpn(String... alpn) {
            return alpn(List.of(alpn));
        }
        @CustomType.Setter
        public Builder defaultSelfSigned(@Nullable Boolean defaultSelfSigned) {

            this.defaultSelfSigned = defaultSelfSigned;
            return this;
        }
        @CustomType.Setter
        public Builder versions(@Nullable List<String> versions) {

            this.versions = versions;
            return this;
        }
        public Builder versions(String... versions) {
            return versions(List.of(versions));
        }
        public FlyTLSOptions build() {
            final var _resultValue = new FlyTLSOptions();
            _resultValue.alpn = alpn;
            _resultValue.defaultSelfSigned = defaultSelfSigned;
            _resultValue.versions = versions;
            return _resultValue;
        }
    }
}
