// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.flyio.flyio.outputs.FlyTempDirVolume;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class FlyVolumeConfig {
    private @Nullable String name;
    private @Nullable FlyTempDirVolume tempDir;

    private FlyVolumeConfig() {}
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    public Optional<FlyTempDirVolume> tempDir() {
        return Optional.ofNullable(this.tempDir);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FlyVolumeConfig defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String name;
        private @Nullable FlyTempDirVolume tempDir;
        public Builder() {}
        public Builder(FlyVolumeConfig defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.tempDir = defaults.tempDir;
        }

        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder tempDir(@Nullable FlyTempDirVolume tempDir) {

            this.tempDir = tempDir;
            return this;
        }
        public FlyVolumeConfig build() {
            final var _resultValue = new FlyVolumeConfig();
            _resultValue.name = name;
            _resultValue.tempDir = tempDir;
            return _resultValue;
        }
    }
}
