# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.3.2/www/docs/static/schema.json
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make gen
builds:
  - binary: pulumi-resource-flyio
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      # The line below MUST align with the module in current provider/go.mod
      - -X github.com/lukeshay/pulumi-flyio/provider/Version={{.Tag }}
    main: ./cmd/pulumi-resource-flyio/
changelog:
  disable: true
release:
  disable: false
  prerelease: auto
snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT"
