// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlyFileArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlyFileArgs Empty = new FlyFileArgs();

    @Import(name="guestPath")
    private @Nullable Output<String> guestPath;

    public Optional<Output<String>> guestPath() {
        return Optional.ofNullable(this.guestPath);
    }

    @Import(name="mode")
    private @Nullable Output<Integer> mode;

    public Optional<Output<Integer>> mode() {
        return Optional.ofNullable(this.mode);
    }

    @Import(name="rawValue")
    private @Nullable Output<String> rawValue;

    public Optional<Output<String>> rawValue() {
        return Optional.ofNullable(this.rawValue);
    }

    @Import(name="secretName")
    private @Nullable Output<String> secretName;

    public Optional<Output<String>> secretName() {
        return Optional.ofNullable(this.secretName);
    }

    private FlyFileArgs() {}

    private FlyFileArgs(FlyFileArgs $) {
        this.guestPath = $.guestPath;
        this.mode = $.mode;
        this.rawValue = $.rawValue;
        this.secretName = $.secretName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlyFileArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlyFileArgs $;

        public Builder() {
            $ = new FlyFileArgs();
        }

        public Builder(FlyFileArgs defaults) {
            $ = new FlyFileArgs(Objects.requireNonNull(defaults));
        }

        public Builder guestPath(@Nullable Output<String> guestPath) {
            $.guestPath = guestPath;
            return this;
        }

        public Builder guestPath(String guestPath) {
            return guestPath(Output.of(guestPath));
        }

        public Builder mode(@Nullable Output<Integer> mode) {
            $.mode = mode;
            return this;
        }

        public Builder mode(Integer mode) {
            return mode(Output.of(mode));
        }

        public Builder rawValue(@Nullable Output<String> rawValue) {
            $.rawValue = rawValue;
            return this;
        }

        public Builder rawValue(String rawValue) {
            return rawValue(Output.of(rawValue));
        }

        public Builder secretName(@Nullable Output<String> secretName) {
            $.secretName = secretName;
            return this;
        }

        public Builder secretName(String secretName) {
            return secretName(Output.of(secretName));
        }

        public FlyFileArgs build() {
            return $;
        }
    }

}
