// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlyHTTPResponseOptionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlyHTTPResponseOptionsArgs Empty = new FlyHTTPResponseOptionsArgs();

    @Import(name="headers")
    private @Nullable Output<Map<String,Map<String,Object>>> headers;

    public Optional<Output<Map<String,Map<String,Object>>>> headers() {
        return Optional.ofNullable(this.headers);
    }

    @Import(name="pristine")
    private @Nullable Output<Boolean> pristine;

    public Optional<Output<Boolean>> pristine() {
        return Optional.ofNullable(this.pristine);
    }

    private FlyHTTPResponseOptionsArgs() {}

    private FlyHTTPResponseOptionsArgs(FlyHTTPResponseOptionsArgs $) {
        this.headers = $.headers;
        this.pristine = $.pristine;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlyHTTPResponseOptionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlyHTTPResponseOptionsArgs $;

        public Builder() {
            $ = new FlyHTTPResponseOptionsArgs();
        }

        public Builder(FlyHTTPResponseOptionsArgs defaults) {
            $ = new FlyHTTPResponseOptionsArgs(Objects.requireNonNull(defaults));
        }

        public Builder headers(@Nullable Output<Map<String,Map<String,Object>>> headers) {
            $.headers = headers;
            return this;
        }

        public Builder headers(Map<String,Map<String,Object>> headers) {
            return headers(Output.of(headers));
        }

        public Builder pristine(@Nullable Output<Boolean> pristine) {
            $.pristine = pristine;
            return this;
        }

        public Builder pristine(Boolean pristine) {
            return pristine(Output.of(pristine));
        }

        public FlyHTTPResponseOptionsArgs build() {
            return $;
        }
    }

}
