// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlyMachineMountArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlyMachineMountArgs Empty = new FlyMachineMountArgs();

    @Import(name="addSizeGb")
    private @Nullable Output<Integer> addSizeGb;

    public Optional<Output<Integer>> addSizeGb() {
        return Optional.ofNullable(this.addSizeGb);
    }

    @Import(name="encrypted")
    private @Nullable Output<Boolean> encrypted;

    public Optional<Output<Boolean>> encrypted() {
        return Optional.ofNullable(this.encrypted);
    }

    @Import(name="extendThresholdPercent")
    private @Nullable Output<Integer> extendThresholdPercent;

    public Optional<Output<Integer>> extendThresholdPercent() {
        return Optional.ofNullable(this.extendThresholdPercent);
    }

    @Import(name="name")
    private @Nullable Output<String> name;

    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    @Import(name="path")
    private @Nullable Output<String> path;

    public Optional<Output<String>> path() {
        return Optional.ofNullable(this.path);
    }

    @Import(name="sizeGb")
    private @Nullable Output<Integer> sizeGb;

    public Optional<Output<Integer>> sizeGb() {
        return Optional.ofNullable(this.sizeGb);
    }

    @Import(name="sizeGbLimit")
    private @Nullable Output<Integer> sizeGbLimit;

    public Optional<Output<Integer>> sizeGbLimit() {
        return Optional.ofNullable(this.sizeGbLimit);
    }

    @Import(name="volume")
    private @Nullable Output<String> volume;

    public Optional<Output<String>> volume() {
        return Optional.ofNullable(this.volume);
    }

    private FlyMachineMountArgs() {}

    private FlyMachineMountArgs(FlyMachineMountArgs $) {
        this.addSizeGb = $.addSizeGb;
        this.encrypted = $.encrypted;
        this.extendThresholdPercent = $.extendThresholdPercent;
        this.name = $.name;
        this.path = $.path;
        this.sizeGb = $.sizeGb;
        this.sizeGbLimit = $.sizeGbLimit;
        this.volume = $.volume;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlyMachineMountArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlyMachineMountArgs $;

        public Builder() {
            $ = new FlyMachineMountArgs();
        }

        public Builder(FlyMachineMountArgs defaults) {
            $ = new FlyMachineMountArgs(Objects.requireNonNull(defaults));
        }

        public Builder addSizeGb(@Nullable Output<Integer> addSizeGb) {
            $.addSizeGb = addSizeGb;
            return this;
        }

        public Builder addSizeGb(Integer addSizeGb) {
            return addSizeGb(Output.of(addSizeGb));
        }

        public Builder encrypted(@Nullable Output<Boolean> encrypted) {
            $.encrypted = encrypted;
            return this;
        }

        public Builder encrypted(Boolean encrypted) {
            return encrypted(Output.of(encrypted));
        }

        public Builder extendThresholdPercent(@Nullable Output<Integer> extendThresholdPercent) {
            $.extendThresholdPercent = extendThresholdPercent;
            return this;
        }

        public Builder extendThresholdPercent(Integer extendThresholdPercent) {
            return extendThresholdPercent(Output.of(extendThresholdPercent));
        }

        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder path(@Nullable Output<String> path) {
            $.path = path;
            return this;
        }

        public Builder path(String path) {
            return path(Output.of(path));
        }

        public Builder sizeGb(@Nullable Output<Integer> sizeGb) {
            $.sizeGb = sizeGb;
            return this;
        }

        public Builder sizeGb(Integer sizeGb) {
            return sizeGb(Output.of(sizeGb));
        }

        public Builder sizeGbLimit(@Nullable Output<Integer> sizeGbLimit) {
            $.sizeGbLimit = sizeGbLimit;
            return this;
        }

        public Builder sizeGbLimit(Integer sizeGbLimit) {
            return sizeGbLimit(Output.of(sizeGbLimit));
        }

        public Builder volume(@Nullable Output<String> volume) {
            $.volume = volume;
            return this;
        }

        public Builder volume(String volume) {
            return volume(Output.of(volume));
        }

        public FlyMachineMountArgs build() {
            return $;
        }
    }

}
