// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlyMachineRestartArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlyMachineRestartArgs Empty = new FlyMachineRestartArgs();

    @Import(name="gpuBidPrice")
    private @Nullable Output<Double> gpuBidPrice;

    public Optional<Output<Double>> gpuBidPrice() {
        return Optional.ofNullable(this.gpuBidPrice);
    }

    @Import(name="maxRetries")
    private @Nullable Output<Integer> maxRetries;

    public Optional<Output<Integer>> maxRetries() {
        return Optional.ofNullable(this.maxRetries);
    }

    @Import(name="policy")
    private @Nullable Output<String> policy;

    public Optional<Output<String>> policy() {
        return Optional.ofNullable(this.policy);
    }

    private FlyMachineRestartArgs() {}

    private FlyMachineRestartArgs(FlyMachineRestartArgs $) {
        this.gpuBidPrice = $.gpuBidPrice;
        this.maxRetries = $.maxRetries;
        this.policy = $.policy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlyMachineRestartArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlyMachineRestartArgs $;

        public Builder() {
            $ = new FlyMachineRestartArgs();
        }

        public Builder(FlyMachineRestartArgs defaults) {
            $ = new FlyMachineRestartArgs(Objects.requireNonNull(defaults));
        }

        public Builder gpuBidPrice(@Nullable Output<Double> gpuBidPrice) {
            $.gpuBidPrice = gpuBidPrice;
            return this;
        }

        public Builder gpuBidPrice(Double gpuBidPrice) {
            return gpuBidPrice(Output.of(gpuBidPrice));
        }

        public Builder maxRetries(@Nullable Output<Integer> maxRetries) {
            $.maxRetries = maxRetries;
            return this;
        }

        public Builder maxRetries(Integer maxRetries) {
            return maxRetries(Output.of(maxRetries));
        }

        public Builder policy(@Nullable Output<String> policy) {
            $.policy = policy;
            return this;
        }

        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        public FlyMachineRestartArgs build() {
            return $;
        }
    }

}
