// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlyMachineMetricsArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlyMachineMetricsArgs Empty = new FlyMachineMetricsArgs();

    @Import(name="path")
    private @Nullable Output<String> path;

    public Optional<Output<String>> path() {
        return Optional.ofNullable(this.path);
    }

    @Import(name="port")
    private @Nullable Output<Integer> port;

    public Optional<Output<Integer>> port() {
        return Optional.ofNullable(this.port);
    }

    private FlyMachineMetricsArgs() {}

    private FlyMachineMetricsArgs(FlyMachineMetricsArgs $) {
        this.path = $.path;
        this.port = $.port;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlyMachineMetricsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlyMachineMetricsArgs $;

        public Builder() {
            $ = new FlyMachineMetricsArgs();
        }

        public Builder(FlyMachineMetricsArgs defaults) {
            $ = new FlyMachineMetricsArgs(Objects.requireNonNull(defaults));
        }

        public Builder path(@Nullable Output<String> path) {
            $.path = path;
            return this;
        }

        public Builder path(String path) {
            return path(Output.of(path));
        }

        public Builder port(@Nullable Output<Integer> port) {
            $.port = port;
            return this;
        }

        public Builder port(Integer port) {
            return port(Output.of(port));
        }

        public FlyMachineMetricsArgs build() {
            return $;
        }
    }

}
