// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.flyio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FlyTempDirVolumeArgs extends com.pulumi.resources.ResourceArgs {

    public static final FlyTempDirVolumeArgs Empty = new FlyTempDirVolumeArgs();

    @Import(name="sizeMb")
    private @Nullable Output<Integer> sizeMb;

    public Optional<Output<Integer>> sizeMb() {
        return Optional.ofNullable(this.sizeMb);
    }

    @Import(name="storageType")
    private @Nullable Output<String> storageType;

    public Optional<Output<String>> storageType() {
        return Optional.ofNullable(this.storageType);
    }

    private FlyTempDirVolumeArgs() {}

    private FlyTempDirVolumeArgs(FlyTempDirVolumeArgs $) {
        this.sizeMb = $.sizeMb;
        this.storageType = $.storageType;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FlyTempDirVolumeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FlyTempDirVolumeArgs $;

        public Builder() {
            $ = new FlyTempDirVolumeArgs();
        }

        public Builder(FlyTempDirVolumeArgs defaults) {
            $ = new FlyTempDirVolumeArgs(Objects.requireNonNull(defaults));
        }

        public Builder sizeMb(@Nullable Output<Integer> sizeMb) {
            $.sizeMb = sizeMb;
            return this;
        }

        public Builder sizeMb(Integer sizeMb) {
            return sizeMb(Output.of(sizeMb));
        }

        public Builder storageType(@Nullable Output<String> storageType) {
            $.storageType = storageType;
            return this;
        }

        public Builder storageType(String storageType) {
            return storageType(Output.of(storageType));
        }

        public FlyTempDirVolumeArgs build() {
            return $;
        }
    }

}
