// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Inputs
{

    public sealed class FlyContainerConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("cmd")]
        private InputList<string>? _cmd;
        public InputList<string> Cmd
        {
            get => _cmd ?? (_cmd = new InputList<string>());
            set => _cmd = value;
        }

        [Input("dependsOn")]
        private InputList<Inputs.FlyContainerDependencyArgs>? _dependsOn;
        public InputList<Inputs.FlyContainerDependencyArgs> DependsOn
        {
            get => _dependsOn ?? (_dependsOn = new InputList<Inputs.FlyContainerDependencyArgs>());
            set => _dependsOn = value;
        }

        [Input("entrypoint")]
        private InputList<string>? _entrypoint;
        public InputList<string> Entrypoint
        {
            get => _entrypoint ?? (_entrypoint = new InputList<string>());
            set => _entrypoint = value;
        }

        [Input("env")]
        private InputMap<string>? _env;
        public InputMap<string> Env
        {
            get => _env ?? (_env = new InputMap<string>());
            set => _env = value;
        }

        [Input("envFrom")]
        private InputList<Inputs.FlyEnvFromArgs>? _envFrom;
        public InputList<Inputs.FlyEnvFromArgs> EnvFrom
        {
            get => _envFrom ?? (_envFrom = new InputList<Inputs.FlyEnvFromArgs>());
            set => _envFrom = value;
        }

        [Input("exec")]
        private InputList<string>? _exec;
        public InputList<string> Exec
        {
            get => _exec ?? (_exec = new InputList<string>());
            set => _exec = value;
        }

        [Input("files")]
        private InputList<Inputs.FlyFileArgs>? _files;
        public InputList<Inputs.FlyFileArgs> Files
        {
            get => _files ?? (_files = new InputList<Inputs.FlyFileArgs>());
            set => _files = value;
        }

        [Input("healthchecks")]
        private InputList<Inputs.FlyContainerHealthcheckArgs>? _healthchecks;
        public InputList<Inputs.FlyContainerHealthcheckArgs> Healthchecks
        {
            get => _healthchecks ?? (_healthchecks = new InputList<Inputs.FlyContainerHealthcheckArgs>());
            set => _healthchecks = value;
        }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("mounts")]
        private InputList<Inputs.FlyContainerMountArgs>? _mounts;
        public InputList<Inputs.FlyContainerMountArgs> Mounts
        {
            get => _mounts ?? (_mounts = new InputList<Inputs.FlyContainerMountArgs>());
            set => _mounts = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("restart")]
        public Input<Inputs.FlyMachineRestartArgs>? Restart { get; set; }

        [Input("secrets")]
        private InputList<Inputs.FlyMachineSecretArgs>? _secrets;
        public InputList<Inputs.FlyMachineSecretArgs> Secrets
        {
            get => _secrets ?? (_secrets = new InputList<Inputs.FlyMachineSecretArgs>());
            set => _secrets = value;
        }

        [Input("stop")]
        public Input<Inputs.FlyStopConfigArgs>? Stop { get; set; }

        [Input("user")]
        public Input<string>? User { get; set; }

        public FlyContainerConfigArgs()
        {
        }
        public static new FlyContainerConfigArgs Empty => new FlyContainerConfigArgs();
    }
}
