// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Inputs
{

    public sealed class FlyHTTPHealthcheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("headers")]
        private InputList<Inputs.FlyMachineHTTPHeaderArgs>? _headers;
        public InputList<Inputs.FlyMachineHTTPHeaderArgs> Headers
        {
            get => _headers ?? (_headers = new InputList<Inputs.FlyMachineHTTPHeaderArgs>());
            set => _headers = value;
        }

        [Input("method")]
        public Input<string>? Method { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("port")]
        public Input<int>? Port { get; set; }

        [Input("scheme")]
        public Input<string>? Scheme { get; set; }

        [Input("tlsServerName")]
        public Input<string>? TlsServerName { get; set; }

        [Input("tlsSkipVerify")]
        public Input<bool>? TlsSkipVerify { get; set; }

        public FlyHTTPHealthcheckArgs()
        {
        }
        public static new FlyHTTPHealthcheckArgs Empty => new FlyHTTPHealthcheckArgs();
    }
}
