// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Flyio.Inputs
{

    public sealed class FlyMachineProcessArgs : global::Pulumi.ResourceArgs
    {
        [Input("cmd")]
        private InputList<string>? _cmd;
        public InputList<string> Cmd
        {
            get => _cmd ?? (_cmd = new InputList<string>());
            set => _cmd = value;
        }

        [Input("entrypoint")]
        private InputList<string>? _entrypoint;
        public InputList<string> Entrypoint
        {
            get => _entrypoint ?? (_entrypoint = new InputList<string>());
            set => _entrypoint = value;
        }

        [Input("env")]
        private InputMap<string>? _env;
        public InputMap<string> Env
        {
            get => _env ?? (_env = new InputMap<string>());
            set => _env = value;
        }

        [Input("envFrom")]
        private InputList<Inputs.FlyEnvFromArgs>? _envFrom;
        public InputList<Inputs.FlyEnvFromArgs> EnvFrom
        {
            get => _envFrom ?? (_envFrom = new InputList<Inputs.FlyEnvFromArgs>());
            set => _envFrom = value;
        }

        [Input("exec")]
        private InputList<string>? _exec;
        public InputList<string> Exec
        {
            get => _exec ?? (_exec = new InputList<string>());
            set => _exec = value;
        }

        [Input("ignoreAppSecrets")]
        public Input<bool>? IgnoreAppSecrets { get; set; }

        [Input("secrets")]
        private InputList<Inputs.FlyMachineSecretArgs>? _secrets;
        public InputList<Inputs.FlyMachineSecretArgs> Secrets
        {
            get => _secrets ?? (_secrets = new InputList<Inputs.FlyMachineSecretArgs>());
            set => _secrets = value;
        }

        [Input("user")]
        public Input<string>? User { get; set; }

        public FlyMachineProcessArgs()
        {
        }
        public static new FlyMachineProcessArgs Empty => new FlyMachineProcessArgs();
    }
}
