// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Flyio.Inputs
{

    public sealed class FlyMachineRestartArgs : global::Pulumi.ResourceArgs
    {
        [Input("maxRetries")]
        public Input<int>? MaxRetries { get; set; }

        [Input("policy")]
        public Input<string>? Policy { get; set; }

        public FlyMachineRestartArgs()
        {
        }
        public static new FlyMachineRestartArgs Empty => new FlyMachineRestartArgs();
    }
}
