// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Inputs
{

    public sealed class FlyStaticArgs : global::Pulumi.ResourceArgs
    {
        [Input("guestPath", required: true)]
        public Input<string> GuestPath { get; set; } = null!;

        [Input("indexDocument")]
        public Input<string>? IndexDocument { get; set; }

        [Input("tigrisBucket")]
        public Input<string>? TigrisBucket { get; set; }

        [Input("urlPrefix", required: true)]
        public Input<string> UrlPrefix { get; set; } = null!;

        public FlyStaticArgs()
        {
        }
        public static new FlyStaticArgs Empty => new FlyStaticArgs();
    }
}
