// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Inputs
{

    public sealed class FlyTempDirVolumeArgs : global::Pulumi.ResourceArgs
    {
        [Input("sizeMb")]
        public Input<int>? SizeMb { get; set; }

        [Input("storageType")]
        public Input<string>? StorageType { get; set; }

        public FlyTempDirVolumeArgs()
        {
        }
        public static new FlyTempDirVolumeArgs Empty => new FlyTempDirVolumeArgs();
    }
}
