// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAppResult {
    private String flyId;
    private String name;
    private String org;
    private String status;

    private GetAppResult() {}
    public String flyId() {
        return this.flyId;
    }
    public String name() {
        return this.name;
    }
    public String org() {
        return this.org;
    }
    public String status() {
        return this.status;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAppResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String flyId;
        private String name;
        private String org;
        private String status;
        public Builder() {}
        public Builder(GetAppResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.flyId = defaults.flyId;
    	      this.name = defaults.name;
    	      this.org = defaults.org;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder flyId(String flyId) {
            if (flyId == null) {
              throw new MissingRequiredPropertyException("GetAppResult", "flyId");
            }
            this.flyId = flyId;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetAppResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder org(String org) {
            if (org == null) {
              throw new MissingRequiredPropertyException("GetAppResult", "org");
            }
            this.org = org;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("GetAppResult", "status");
            }
            this.status = status;
            return this;
        }
        public GetAppResult build() {
            final var _resultValue = new GetAppResult();
            _resultValue.flyId = flyId;
            _resultValue.name = name;
            _resultValue.org = org;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
