// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Outputs
{

    [OutputType]
    public sealed class MachineArgs
    {
        public readonly string App;
        public readonly PulumiFlyio.Flyio.Flyio.Outputs.FlyMachineConfig Config;
        public readonly string? DeploymentStrategy;
        public readonly int? LeaseTtl;
        public readonly bool? Lsvd;
        public readonly string? Name;
        public readonly string? Region;
        public readonly bool? SkipLaunch;
        public readonly bool? SkipServiceRegistration;

        [OutputConstructor]
        private MachineArgs(
            string app,

            PulumiFlyio.Flyio.Flyio.Outputs.FlyMachineConfig config,

            string? deploymentStrategy,

            int? leaseTtl,

            bool? lsvd,

            string? name,

            string? region,

            bool? skipLaunch,

            bool? skipServiceRegistration)
        {
            App = app;
            Config = config;
            DeploymentStrategy = deploymentStrategy;
            LeaseTtl = leaseTtl;
            Lsvd = lsvd;
            Name = name;
            Region = region;
            SkipLaunch = skipLaunch;
            SkipServiceRegistration = skipServiceRegistration;
        }
    }
}
