// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Outputs
{

    [OutputType]
    public sealed class VolumeArgs
    {
        public readonly string AppName;
        public readonly bool? AutoBackupEnabled;
        public readonly Pulumi.Flyio.Flyio.Outputs.FlyMachineGuest? Compute;
        public readonly string? ComputeImage;
        public readonly bool? Encrypted;
        public readonly string? Fstype;
        public readonly bool? MachinesOnly;
        public readonly string? Name;
        public readonly string? Region;
        public readonly bool? RequireUniqueZone;
        public readonly int? SizeGb;
        public readonly string? SnapshotId;
        public readonly int? SnapshotRetention;
        public readonly string? SourceVolumeId;

        [OutputConstructor]
        private VolumeArgs(
            string appName,

            bool? autoBackupEnabled,

            Pulumi.Flyio.Flyio.Outputs.FlyMachineGuest? compute,

            string? computeImage,

            bool? encrypted,

            string? fstype,

            bool? machinesOnly,

            string? name,

            string? region,

            bool? requireUniqueZone,

            int? sizeGb,

            string? snapshotId,

            int? snapshotRetention,

            string? sourceVolumeId)
        {
            AppName = appName;
            AutoBackupEnabled = autoBackupEnabled;
            Compute = compute;
            ComputeImage = computeImage;
            Encrypted = encrypted;
            Fstype = fstype;
            MachinesOnly = machinesOnly;
            Name = name;
            Region = region;
            RequireUniqueZone = requireUniqueZone;
            SizeGb = sizeGb;
            SnapshotId = snapshotId;
            SnapshotRetention = snapshotRetention;
            SourceVolumeId = sourceVolumeId;
        }
    }
}
