// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyDnsForwardRule
    {
        public readonly string? Addr;
        public readonly string? Basename;

        [OutputConstructor]
        private FlyDnsForwardRule(
            string? addr,

            string? basename)
        {
            Addr = addr;
            Basename = basename;
        }
    }
}
