// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyEnvFrom
    {
        public readonly string? EnvVar;
        public readonly string? FieldRef;

        [OutputConstructor]
        private FlyEnvFrom(
            string? envVar,

            string? fieldRef)
        {
            EnvVar = envVar;
            FieldRef = fieldRef;
        }
    }
}
