// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyFile
    {
        public readonly string? GuestPath;
        public readonly int? Mode;
        public readonly string? RawValue;
        public readonly string? SecretName;

        [OutputConstructor]
        private FlyFile(
            string? guestPath,

            int? mode,

            string? rawValue,

            string? secretName)
        {
            GuestPath = guestPath;
            Mode = mode;
            RawValue = rawValue;
            SecretName = secretName;
        }
    }
}
