// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyMachineCheck
    {
        public readonly string? GracePeriod;
        public readonly ImmutableArray<Outputs.FlyMachineHTTPHeader> Headers;
        public readonly string? Interval;
        public readonly string? Kind;
        public readonly string? Method;
        public readonly string? Path;
        public readonly int? Port;
        public readonly string? Protocol;
        public readonly string? Timeout;
        public readonly string? TlsServerName;
        public readonly bool? TlsSkipVerify;
        public readonly string? Type;

        [OutputConstructor]
        private FlyMachineCheck(
            string? gracePeriod,

            ImmutableArray<Outputs.FlyMachineHTTPHeader> headers,

            string? interval,

            string? kind,

            string? method,

            string? path,

            int? port,

            string? protocol,

            string? timeout,

            string? tlsServerName,

            bool? tlsSkipVerify,

            string? type)
        {
            GracePeriod = gracePeriod;
            Headers = headers;
            Interval = interval;
            Kind = kind;
            Method = method;
            Path = path;
            Port = port;
            Protocol = protocol;
            Timeout = timeout;
            TlsServerName = tlsServerName;
            TlsSkipVerify = tlsSkipVerify;
            Type = type;
        }
    }
}
