// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyMachineServiceConcurrency
    {
        public readonly int? HardLimit;
        public readonly int? SoftLimit;
        public readonly string? Type;

        [OutputConstructor]
        private FlyMachineServiceConcurrency(
            int? hardLimit,

            int? softLimit,

            string? type)
        {
            HardLimit = hardLimit;
            SoftLimit = softLimit;
            Type = type;
        }
    }
}
