// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyMachineMount
    {
        public readonly int? AddSizeGb;
        public readonly bool? Encrypted;
        public readonly int? ExtendThresholdPercent;
        public readonly string? Name;
        public readonly string? Path;
        public readonly int? SizeGb;
        public readonly int? SizeGbLimit;
        public readonly string? Volume;

        [OutputConstructor]
        private FlyMachineMount(
            int? addSizeGb,

            bool? encrypted,

            int? extendThresholdPercent,

            string? name,

            string? path,

            int? sizeGb,

            int? sizeGbLimit,

            string? volume)
        {
            AddSizeGb = addSizeGb;
            Encrypted = encrypted;
            ExtendThresholdPercent = extendThresholdPercent;
            Name = name;
            Path = path;
            SizeGb = sizeGb;
            SizeGbLimit = sizeGbLimit;
            Volume = volume;
        }
    }
}
