// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyMachineMetrics
    {
        public readonly bool? Https;
        public readonly string? Path;
        public readonly int? Port;

        [OutputConstructor]
        private FlyMachineMetrics(
            bool? https,

            string? path,

            int? port)
        {
            Https = https;
            Path = path;
            Port = port;
        }
    }
}
