// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyStatic
    {
        public readonly string GuestPath;
        public readonly string? TigrisBucket;
        public readonly string UrlPrefix;

        [OutputConstructor]
        private FlyStatic(
            string guestPath,

            string? tigrisBucket,

            string urlPrefix)
        {
            GuestPath = guestPath;
            TigrisBucket = tigrisBucket;
            UrlPrefix = urlPrefix;
        }
    }
}
