// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PulumiFlyio.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class FlyVolumeConfig
    {
        public readonly string? Name;
        public readonly Outputs.FlyTempDirVolume? TempDir;

        [OutputConstructor]
        private FlyVolumeConfig(
            string? name,

            Outputs.FlyTempDirVolume? tempDir)
        {
            Name = name;
            TempDir = tempDir;
        }
    }
}
