// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Flyio.Flyio.Outputs
{

    [OutputType]
    public sealed class Organization
    {
        public readonly string Name;
        public readonly string Slug;

        [OutputConstructor]
        private Organization(
            string name,

            string slug)
        {
            Name = name;
            Slug = slug;
        }
    }
}
