// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/lukeshay/pulumi-flyio/sdk/go/flyio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// API key for the Fly.io API.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "flyio:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "FLY_API_TOKEN", "FLY_TOKEN", "FLY_API_KEY", "FLY_KEY"); d != nil {
		value = d.(string)
	}
	return value
}
