// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class AppArgs extends com.pulumi.resources.ResourceArgs {

    public static final AppArgs Empty = new AppArgs();

    @Import(name="enableSubdomains")
    private @Nullable Output<Boolean> enableSubdomains;

    public Optional<Output<Boolean>> enableSubdomains() {
        return Optional.ofNullable(this.enableSubdomains);
    }

    @Import(name="name", required=true)
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }

    @Import(name="network")
    private @Nullable Output<String> network;

    public Optional<Output<String>> network() {
        return Optional.ofNullable(this.network);
    }

    @Import(name="org", required=true)
    private Output<String> org;

    public Output<String> org() {
        return this.org;
    }

    private AppArgs() {}

    private AppArgs(AppArgs $) {
        this.enableSubdomains = $.enableSubdomains;
        this.name = $.name;
        this.network = $.network;
        this.org = $.org;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(AppArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private AppArgs $;

        public Builder() {
            $ = new AppArgs();
        }

        public Builder(AppArgs defaults) {
            $ = new AppArgs(Objects.requireNonNull(defaults));
        }

        public Builder enableSubdomains(@Nullable Output<Boolean> enableSubdomains) {
            $.enableSubdomains = enableSubdomains;
            return this;
        }

        public Builder enableSubdomains(Boolean enableSubdomains) {
            return enableSubdomains(Output.of(enableSubdomains));
        }

        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder network(@Nullable Output<String> network) {
            $.network = network;
            return this;
        }

        public Builder network(String network) {
            return network(Output.of(network));
        }

        public Builder org(Output<String> org) {
            $.org = org;
            return this;
        }

        public Builder org(String org) {
            return org(Output.of(org));
        }

        public AppArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("AppArgs", "name");
            }
            if ($.org == null) {
                throw new MissingRequiredPropertyException("AppArgs", "org");
            }
            return $;
        }
    }

}
