// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class CertificateIssuanceWaiterArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertificateIssuanceWaiterArgs Empty = new CertificateIssuanceWaiterArgs();

    /**
     * The name of the Fly app that the certificate is associated with.
     * 
     */
    @Import(name="app", required=true)
    private Output<String> app;

    /**
     * @return The name of the Fly app that the certificate is associated with.
     * 
     */
    public Output<String> app() {
        return this.app;
    }

    /**
     * The hostname for the certificate (e.g., example.com).
     * 
     */
    @Import(name="hostname", required=true)
    private Output<String> hostname;

    /**
     * @return The hostname for the certificate (e.g., example.com).
     * 
     */
    public Output<String> hostname() {
        return this.hostname;
    }

    /**
     * The maximum time to wait for the certificate to be fully issued. Formatted like 5s, 5m, etc.
     * 
     */
    @Import(name="timeout", required=true)
    private Output<Integer> timeout;

    /**
     * @return The maximum time to wait for the certificate to be fully issued. Formatted like 5s, 5m, etc.
     * 
     */
    public Output<Integer> timeout() {
        return this.timeout;
    }

    private CertificateIssuanceWaiterArgs() {}

    private CertificateIssuanceWaiterArgs(CertificateIssuanceWaiterArgs $) {
        this.app = $.app;
        this.hostname = $.hostname;
        this.timeout = $.timeout;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertificateIssuanceWaiterArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertificateIssuanceWaiterArgs $;

        public Builder() {
            $ = new CertificateIssuanceWaiterArgs();
        }

        public Builder(CertificateIssuanceWaiterArgs defaults) {
            $ = new CertificateIssuanceWaiterArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param app The name of the Fly app that the certificate is associated with.
         * 
         * @return builder
         * 
         */
        public Builder app(Output<String> app) {
            $.app = app;
            return this;
        }

        /**
         * @param app The name of the Fly app that the certificate is associated with.
         * 
         * @return builder
         * 
         */
        public Builder app(String app) {
            return app(Output.of(app));
        }

        /**
         * @param hostname The hostname for the certificate (e.g., example.com).
         * 
         * @return builder
         * 
         */
        public Builder hostname(Output<String> hostname) {
            $.hostname = hostname;
            return this;
        }

        /**
         * @param hostname The hostname for the certificate (e.g., example.com).
         * 
         * @return builder
         * 
         */
        public Builder hostname(String hostname) {
            return hostname(Output.of(hostname));
        }

        /**
         * @param timeout The maximum time to wait for the certificate to be fully issued. Formatted like 5s, 5m, etc.
         * 
         * @return builder
         * 
         */
        public Builder timeout(Output<Integer> timeout) {
            $.timeout = timeout;
            return this;
        }

        /**
         * @param timeout The maximum time to wait for the certificate to be fully issued. Formatted like 5s, 5m, etc.
         * 
         * @return builder
         * 
         */
        public Builder timeout(Integer timeout) {
            return timeout(Output.of(timeout));
        }

        public CertificateIssuanceWaiterArgs build() {
            if ($.app == null) {
                throw new MissingRequiredPropertyException("CertificateIssuanceWaiterArgs", "app");
            }
            if ($.hostname == null) {
                throw new MissingRequiredPropertyException("CertificateIssuanceWaiterArgs", "hostname");
            }
            if ($.timeout == null) {
                throw new MissingRequiredPropertyException("CertificateIssuanceWaiterArgs", "timeout");
            }
            return $;
        }
    }

}
