// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class CertificateArgs extends com.pulumi.resources.ResourceArgs {

    public static final CertificateArgs Empty = new CertificateArgs();

    @Import(name="app", required=true)
    private Output<String> app;

    public Output<String> app() {
        return this.app;
    }

    @Import(name="hostname", required=true)
    private Output<String> hostname;

    public Output<String> hostname() {
        return this.hostname;
    }

    private CertificateArgs() {}

    private CertificateArgs(CertificateArgs $) {
        this.app = $.app;
        this.hostname = $.hostname;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(CertificateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private CertificateArgs $;

        public Builder() {
            $ = new CertificateArgs();
        }

        public Builder(CertificateArgs defaults) {
            $ = new CertificateArgs(Objects.requireNonNull(defaults));
        }

        public Builder app(Output<String> app) {
            $.app = app;
            return this;
        }

        public Builder app(String app) {
            return app(Output.of(app));
        }

        public Builder hostname(Output<String> hostname) {
            $.hostname = hostname;
            return this;
        }

        public Builder hostname(String hostname) {
            return hostname(Output.of(hostname));
        }

        public CertificateArgs build() {
            if ($.app == null) {
                throw new MissingRequiredPropertyException("CertificateArgs", "app");
            }
            if ($.hostname == null) {
                throw new MissingRequiredPropertyException("CertificateArgs", "hostname");
            }
            return $;
        }
    }

}
