// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("flyio");
/**
 * API key for the Fly.io API.
 * 
 */
    public Optional<String> token() {
        return Codegen.stringProp("token").config(config).env("FLY_API_TOKEN", "FLY_TOKEN", "FLY_API_KEY", "FLY_KEY").def("").get();
    }
}
