// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.flyio.Utilities;
import com.pulumi.flyio.inputs.GetAppArgs;
import com.pulumi.flyio.inputs.GetAppPlainArgs;
import com.pulumi.flyio.outputs.GetAppResult;
import java.util.concurrent.CompletableFuture;

public final class FlyioFunctions {
    /**
     * Gets the state of a Fly.io app.
     * 
     */
    public static Output<GetAppResult> getApp(GetAppArgs args) {
        return getApp(args, InvokeOptions.Empty);
    }
    /**
     * Gets the state of a Fly.io app.
     * 
     */
    public static CompletableFuture<GetAppResult> getAppPlain(GetAppPlainArgs args) {
        return getAppPlain(args, InvokeOptions.Empty);
    }
    /**
     * Gets the state of a Fly.io app.
     * 
     */
    public static Output<GetAppResult> getApp(GetAppArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("flyio:index:getApp", TypeShape.of(GetAppResult.class), args, Utilities.withVersion(options));
    }
    /**
     * Gets the state of a Fly.io app.
     * 
     */
    public static CompletableFuture<GetAppResult> getAppPlain(GetAppPlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("flyio:index:getApp", TypeShape.of(GetAppResult.class), args, Utilities.withVersion(options));
    }
}
