// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IPArgs extends com.pulumi.resources.ResourceArgs {

    public static final IPArgs Empty = new IPArgs();

    @Import(name="addrType", required=true)
    private Output<String> addrType;

    public Output<String> addrType() {
        return this.addrType;
    }

    @Import(name="app", required=true)
    private Output<String> app;

    public Output<String> app() {
        return this.app;
    }

    @Import(name="network")
    private @Nullable Output<String> network;

    public Optional<Output<String>> network() {
        return Optional.ofNullable(this.network);
    }

    @Import(name="region", required=true)
    private Output<String> region;

    public Output<String> region() {
        return this.region;
    }

    private IPArgs() {}

    private IPArgs(IPArgs $) {
        this.addrType = $.addrType;
        this.app = $.app;
        this.network = $.network;
        this.region = $.region;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IPArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IPArgs $;

        public Builder() {
            $ = new IPArgs();
        }

        public Builder(IPArgs defaults) {
            $ = new IPArgs(Objects.requireNonNull(defaults));
        }

        public Builder addrType(Output<String> addrType) {
            $.addrType = addrType;
            return this;
        }

        public Builder addrType(String addrType) {
            return addrType(Output.of(addrType));
        }

        public Builder app(Output<String> app) {
            $.app = app;
            return this;
        }

        public Builder app(String app) {
            return app(Output.of(app));
        }

        public Builder network(@Nullable Output<String> network) {
            $.network = network;
            return this;
        }

        public Builder network(String network) {
            return network(Output.of(network));
        }

        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        public Builder region(String region) {
            return region(Output.of(region));
        }

        public IPArgs build() {
            if ($.addrType == null) {
                throw new MissingRequiredPropertyException("IPArgs", "addrType");
            }
            if ($.app == null) {
                throw new MissingRequiredPropertyException("IPArgs", "app");
            }
            if ($.region == null) {
                throw new MissingRequiredPropertyException("IPArgs", "region");
            }
            return $;
        }
    }

}
