// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.flyio.time.outputs;

import com.pulumi.core.annotations.CustomType;
import java.util.Objects;

@CustomType
public final class Time {
    private Time() {}

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Time defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        public Builder() {}
        public Builder(Time defaults) {
    	      Objects.requireNonNull(defaults);
        }

        public Time build() {
            final var _resultValue = new Time();
            return _resultValue;
        }
    }
}
