// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package flyio

import (
	"context"
	"reflect"

	"github.com/lukeshay/pulumi-flyio/sdk/go/flyio/flyio"
	"github.com/lukeshay/pulumi-flyio/sdk/go/flyio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type AppArgsType struct {
	// Whether to enable subdomains for the application.
	EnableSubdomains *bool `pulumi:"enableSubdomains"`
	// The name of the Fly.io application.
	Name string `pulumi:"name"`
	// The network the application belongs to.
	Network *string `pulumi:"network"`
	// The organization the application belongs to.
	Org string `pulumi:"org"`
}

type AppArgsTypeOutput struct{ *pulumi.OutputState }

func (AppArgsTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AppArgsType)(nil)).Elem()
}

func (o AppArgsTypeOutput) ToAppArgsTypeOutput() AppArgsTypeOutput {
	return o
}

func (o AppArgsTypeOutput) ToAppArgsTypeOutputWithContext(ctx context.Context) AppArgsTypeOutput {
	return o
}

// Whether to enable subdomains for the application.
func (o AppArgsTypeOutput) EnableSubdomains() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v AppArgsType) *bool { return v.EnableSubdomains }).(pulumi.BoolPtrOutput)
}

// The name of the Fly.io application.
func (o AppArgsTypeOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v AppArgsType) string { return v.Name }).(pulumi.StringOutput)
}

// The network the application belongs to.
func (o AppArgsTypeOutput) Network() pulumi.StringPtrOutput {
	return o.ApplyT(func(v AppArgsType) *string { return v.Network }).(pulumi.StringPtrOutput)
}

// The organization the application belongs to.
func (o AppArgsTypeOutput) Org() pulumi.StringOutput {
	return o.ApplyT(func(v AppArgsType) string { return v.Org }).(pulumi.StringOutput)
}

type CertificateArgsType struct {
	// The name of the Fly app to add the certificate to.
	App string `pulumi:"app"`
	// The hostname for the certificate (e.g., example.com).
	Hostname string `pulumi:"hostname"`
}

type CertificateArgsTypeOutput struct{ *pulumi.OutputState }

func (CertificateArgsTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CertificateArgsType)(nil)).Elem()
}

func (o CertificateArgsTypeOutput) ToCertificateArgsTypeOutput() CertificateArgsTypeOutput {
	return o
}

func (o CertificateArgsTypeOutput) ToCertificateArgsTypeOutputWithContext(ctx context.Context) CertificateArgsTypeOutput {
	return o
}

// The name of the Fly app to add the certificate to.
func (o CertificateArgsTypeOutput) App() pulumi.StringOutput {
	return o.ApplyT(func(v CertificateArgsType) string { return v.App }).(pulumi.StringOutput)
}

// The hostname for the certificate (e.g., example.com).
func (o CertificateArgsTypeOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v CertificateArgsType) string { return v.Hostname }).(pulumi.StringOutput)
}

type CertificateIssuanceWaiterArgsType struct {
	// The name of the Fly app that the certificate is associated with.
	App string `pulumi:"app"`
	// The hostname for the certificate (e.g., example.com).
	Hostname string `pulumi:"hostname"`
	// The maximum time to wait for the certificate to be fully issued. Formatted like 5s, 5m, etc.
	Timeout int `pulumi:"timeout"`
}

type CertificateIssuanceWaiterArgsTypeOutput struct{ *pulumi.OutputState }

func (CertificateIssuanceWaiterArgsTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*CertificateIssuanceWaiterArgsType)(nil)).Elem()
}

func (o CertificateIssuanceWaiterArgsTypeOutput) ToCertificateIssuanceWaiterArgsTypeOutput() CertificateIssuanceWaiterArgsTypeOutput {
	return o
}

func (o CertificateIssuanceWaiterArgsTypeOutput) ToCertificateIssuanceWaiterArgsTypeOutputWithContext(ctx context.Context) CertificateIssuanceWaiterArgsTypeOutput {
	return o
}

// The name of the Fly app that the certificate is associated with.
func (o CertificateIssuanceWaiterArgsTypeOutput) App() pulumi.StringOutput {
	return o.ApplyT(func(v CertificateIssuanceWaiterArgsType) string { return v.App }).(pulumi.StringOutput)
}

// The hostname for the certificate (e.g., example.com).
func (o CertificateIssuanceWaiterArgsTypeOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v CertificateIssuanceWaiterArgsType) string { return v.Hostname }).(pulumi.StringOutput)
}

// The maximum time to wait for the certificate to be fully issued. Formatted like 5s, 5m, etc.
func (o CertificateIssuanceWaiterArgsTypeOutput) Timeout() pulumi.IntOutput {
	return o.ApplyT(func(v CertificateIssuanceWaiterArgsType) int { return v.Timeout }).(pulumi.IntOutput)
}

type IPArgsType struct {
	// The type of IP address (v4 or v6).
	AddrType string `pulumi:"addrType"`
	// The name of the Fly.io application to allocate the IP address for.
	App string `pulumi:"app"`
	// The network to allocate the IP address in.
	Network *string `pulumi:"network"`
	// The region to allocate the IP address in.
	Region string `pulumi:"region"`
}

type IPArgsTypeOutput struct{ *pulumi.OutputState }

func (IPArgsTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*IPArgsType)(nil)).Elem()
}

func (o IPArgsTypeOutput) ToIPArgsTypeOutput() IPArgsTypeOutput {
	return o
}

func (o IPArgsTypeOutput) ToIPArgsTypeOutputWithContext(ctx context.Context) IPArgsTypeOutput {
	return o
}

// The type of IP address (v4 or v6).
func (o IPArgsTypeOutput) AddrType() pulumi.StringOutput {
	return o.ApplyT(func(v IPArgsType) string { return v.AddrType }).(pulumi.StringOutput)
}

// The name of the Fly.io application to allocate the IP address for.
func (o IPArgsTypeOutput) App() pulumi.StringOutput {
	return o.ApplyT(func(v IPArgsType) string { return v.App }).(pulumi.StringOutput)
}

// The network to allocate the IP address in.
func (o IPArgsTypeOutput) Network() pulumi.StringPtrOutput {
	return o.ApplyT(func(v IPArgsType) *string { return v.Network }).(pulumi.StringPtrOutput)
}

// The region to allocate the IP address in.
func (o IPArgsTypeOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v IPArgsType) string { return v.Region }).(pulumi.StringOutput)
}

type MachineArgsType struct {
	// The Fly.io application to deploy the machine to.
	App    string                 `pulumi:"app"`
	Config flyio.FlyMachineConfig `pulumi:"config"`
	// The deployment strategy for the machine.
	DeploymentStrategy      *string `pulumi:"deploymentStrategy"`
	LeaseTtl                *int    `pulumi:"leaseTtl"`
	Lsvd                    *bool   `pulumi:"lsvd"`
	Name                    *string `pulumi:"name"`
	Region                  *string `pulumi:"region"`
	SkipLaunch              *bool   `pulumi:"skipLaunch"`
	SkipServiceRegistration *bool   `pulumi:"skipServiceRegistration"`
}

type MachineArgsTypeOutput struct{ *pulumi.OutputState }

func (MachineArgsTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*MachineArgsType)(nil)).Elem()
}

func (o MachineArgsTypeOutput) ToMachineArgsTypeOutput() MachineArgsTypeOutput {
	return o
}

func (o MachineArgsTypeOutput) ToMachineArgsTypeOutputWithContext(ctx context.Context) MachineArgsTypeOutput {
	return o
}

// The Fly.io application to deploy the machine to.
func (o MachineArgsTypeOutput) App() pulumi.StringOutput {
	return o.ApplyT(func(v MachineArgsType) string { return v.App }).(pulumi.StringOutput)
}

func (o MachineArgsTypeOutput) Config() flyio.FlyMachineConfigOutput {
	return o.ApplyT(func(v MachineArgsType) flyio.FlyMachineConfig { return v.Config }).(flyio.FlyMachineConfigOutput)
}

// The deployment strategy for the machine.
func (o MachineArgsTypeOutput) DeploymentStrategy() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MachineArgsType) *string { return v.DeploymentStrategy }).(pulumi.StringPtrOutput)
}

func (o MachineArgsTypeOutput) LeaseTtl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v MachineArgsType) *int { return v.LeaseTtl }).(pulumi.IntPtrOutput)
}

func (o MachineArgsTypeOutput) Lsvd() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v MachineArgsType) *bool { return v.Lsvd }).(pulumi.BoolPtrOutput)
}

func (o MachineArgsTypeOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MachineArgsType) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o MachineArgsTypeOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MachineArgsType) *string { return v.Region }).(pulumi.StringPtrOutput)
}

func (o MachineArgsTypeOutput) SkipLaunch() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v MachineArgsType) *bool { return v.SkipLaunch }).(pulumi.BoolPtrOutput)
}

func (o MachineArgsTypeOutput) SkipServiceRegistration() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v MachineArgsType) *bool { return v.SkipServiceRegistration }).(pulumi.BoolPtrOutput)
}

type VolumeArgsType struct {
	// The Fly.io application to attach the volume to.
	App string `pulumi:"app"`
	// Whether to enable automatic backups for the volume.
	AutoBackupEnabled *bool                  `pulumi:"autoBackupEnabled"`
	Compute           *flyio.FlyMachineGuest `pulumi:"compute"`
	ComputeImage      *string                `pulumi:"computeImage"`
	Encrypted         *bool                  `pulumi:"encrypted"`
	Fstype            *string                `pulumi:"fstype"`
	Name              *string                `pulumi:"name"`
	Region            *string                `pulumi:"region"`
	RequireUniqueZone *bool                  `pulumi:"requireUniqueZone"`
	SizeGb            *int                   `pulumi:"sizeGb"`
	SnapshotId        *string                `pulumi:"snapshotId"`
	SnapshotRetention *int                   `pulumi:"snapshotRetention"`
	SourceVolumeId    *string                `pulumi:"sourceVolumeId"`
	UniqueZoneAppWide *bool                  `pulumi:"uniqueZoneAppWide"`
}

type VolumeArgsTypeOutput struct{ *pulumi.OutputState }

func (VolumeArgsTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*VolumeArgsType)(nil)).Elem()
}

func (o VolumeArgsTypeOutput) ToVolumeArgsTypeOutput() VolumeArgsTypeOutput {
	return o
}

func (o VolumeArgsTypeOutput) ToVolumeArgsTypeOutputWithContext(ctx context.Context) VolumeArgsTypeOutput {
	return o
}

// The Fly.io application to attach the volume to.
func (o VolumeArgsTypeOutput) App() pulumi.StringOutput {
	return o.ApplyT(func(v VolumeArgsType) string { return v.App }).(pulumi.StringOutput)
}

// Whether to enable automatic backups for the volume.
func (o VolumeArgsTypeOutput) AutoBackupEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *bool { return v.AutoBackupEnabled }).(pulumi.BoolPtrOutput)
}

func (o VolumeArgsTypeOutput) Compute() flyio.FlyMachineGuestPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *flyio.FlyMachineGuest { return v.Compute }).(flyio.FlyMachineGuestPtrOutput)
}

func (o VolumeArgsTypeOutput) ComputeImage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *string { return v.ComputeImage }).(pulumi.StringPtrOutput)
}

func (o VolumeArgsTypeOutput) Encrypted() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *bool { return v.Encrypted }).(pulumi.BoolPtrOutput)
}

func (o VolumeArgsTypeOutput) Fstype() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *string { return v.Fstype }).(pulumi.StringPtrOutput)
}

func (o VolumeArgsTypeOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o VolumeArgsTypeOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *string { return v.Region }).(pulumi.StringPtrOutput)
}

func (o VolumeArgsTypeOutput) RequireUniqueZone() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *bool { return v.RequireUniqueZone }).(pulumi.BoolPtrOutput)
}

func (o VolumeArgsTypeOutput) SizeGb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *int { return v.SizeGb }).(pulumi.IntPtrOutput)
}

func (o VolumeArgsTypeOutput) SnapshotId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *string { return v.SnapshotId }).(pulumi.StringPtrOutput)
}

func (o VolumeArgsTypeOutput) SnapshotRetention() pulumi.IntPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *int { return v.SnapshotRetention }).(pulumi.IntPtrOutput)
}

func (o VolumeArgsTypeOutput) SourceVolumeId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *string { return v.SourceVolumeId }).(pulumi.StringPtrOutput)
}

func (o VolumeArgsTypeOutput) UniqueZoneAppWide() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v VolumeArgsType) *bool { return v.UniqueZoneAppWide }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(AppArgsTypeOutput{})
	pulumi.RegisterOutputType(CertificateArgsTypeOutput{})
	pulumi.RegisterOutputType(CertificateIssuanceWaiterArgsTypeOutput{})
	pulumi.RegisterOutputType(IPArgsTypeOutput{})
	pulumi.RegisterOutputType(MachineArgsTypeOutput{})
	pulumi.RegisterOutputType(VolumeArgsTypeOutput{})
}
