// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Gets the state of a Fly.io app.
 */
export function getApp(args: GetAppArgs, opts?: pulumi.InvokeOptions): Promise<GetAppResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("flyio:index:getApp", {
        "name": args.name,
    }, opts);
}

export interface GetAppArgs {
    /**
     * The name of the app.
     */
    name: string;
}

export interface GetAppResult {
    readonly flyId: string;
    readonly name: string;
    readonly org: string;
    readonly status: string;
}
/**
 * Gets the state of a Fly.io app.
 */
export function getAppOutput(args: GetAppOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAppResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("flyio:index:getApp", {
        "name": args.name,
    }, opts);
}

export interface GetAppOutputArgs {
    /**
     * The name of the app.
     */
    name: pulumi.Input<string>;
}
